import { useState, useEffect } from "react";
import { supabase } from "./supabaseClient";

const INK = "#1E2B28";
const PAPER = "#FAF8F3";
const STAMP = "#B5451F";
const FOREST = "#2B6653";
const LINE = "#DCD6C7";

export default function AuthGate({ children }) {
  const [session, setSession] = useState(undefined);
    const [mode, setMode] = useState("signin");
      const [email, setEmail] = useState("");
        const [password, setPassword] = useState("");
          const [error, setError] = useState("");
            const [info, setInfo] = useState("");
              const [busy, setBusy] = useState(false);

                useEffect(() => {
                    supabase.auth.getSession().then(({ data }) => setSession(data.session));
                        const { data: listener } = supabase.auth.onAuthStateChange((_event, newSession) => {
                              setSession(newSession);
                                  });
                                      return () => listener.subscription.unsubscribe();
                                        }, []);

                                          const handleSubmit = async (e) => {
                                              e.preventDefault();
                                                  setError("");
                                                      setInfo("");
                                                          setBusy(true);
                                                              if (mode === "signup") {
                                                                    const { error: signUpError } = await supabase.auth.signUp({ email, password });
                                                                          if (signUpError) setError(signUpError.message);
                                                                                else setInfo("Check your email to confirm your account, then sign in.");
                                                                                    } else {
                                                                                          const { error: signInError } = await supabase.auth.signInWithPassword({ email, password });
                                                                                                if (signInError) setError(signInError.message);
                                                                                                    }
                                                                                                        setBusy(false);
                                                                                                          };
                                                                                                          
                                                                                                            const handleLogout = async () => {
                                                                                                                await supabase.auth.signOut();
                                                                                                                  };
                                                                                                                  
                                                                                                                    if (session === undefined) {
                                                                                                                        return (
                                                                                                                              <div className="min-h-screen w-full flex items-center justify-center" style={{ background: PAPER, color: INK }}>
                                                                                                                                      <p className="font-mono text-sm" style={{ opacity: 0.6 }}>Loading...</p>
                                                                                                                                            </div>
                                                                                                                                                );
                                                                                                                                                  }
                                                                                                                                                  
                                                                                                                                                    if (!session) {
                                                                                                                                                        return (
                                                                                                                                                              <div className="min-h-screen w-full flex items-center justify-center px-5" style={{ background: PAPER, color: INK }}>
                                                                                                                                                                      <div className="w-full max-w-sm rounded-2xl border-2 p-6" style={{ borderColor: LINE }}>
                                                                                                                                                                                <h1 className="text-2xl font-bold mb-1">The Landing Money Plan</h1>
                                                                                                                                                                                          <p className="text-sm mb-6" style={{ opacity: 0.7 }}>
                                                                                                                                                                                                      {mode === "signup" ? "Create an account to save your numbers." : "Sign in to pick up where you left off."}
                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                          <form onSubmit={handleSubmit} className="flex flex-col gap-3">
                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                    type="email"
                                                                                                                                                                                                                                                                  required
                                                                                                                                                                                                                                                                                value={email}
                                                                                                                                                                                                                                                                                              onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                            placeholder="you@email.com"
                                                                                                                                                                                                                                                                                                                          className="px-4 py-3 rounded-full border-2 outline-none font-mono text-sm"
                                                                                                                                                                                                                                                                                                                                        style={{ borderColor: LINE, background: "white" }}
                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                              type="password"
                                                                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                                                                          minLength={6}
                                                                                                                                                                                                                                                                                                                                                                                                                        value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    placeholder="Password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="px-4 py-3 rounded-full border-2 outline-none font-mono text-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{ borderColor: LINE, background: "white" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {error && <p className="text-xs" style={{ color: STAMP }}>{error}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {info && <p className="text-xs" style={{ color: FOREST }}>{info}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            disabled={busy}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="px-6 py-3 rounded-full font-bold text-sm mt-1"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{ background: INK, color: PAPER, opacity: busy ? 0.6 : 1 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {busy ? "Please wait..." : mode === "signup" ? "Create account" : "Sign in"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => { setMode(mode === "signup" ? "signin" : "signup"); setError(""); setInfo(""); }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="mt-4 text-xs underline"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{ color: INK, opacity: 0.7 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {mode === "signup" ? "Already have an account? Sign in" : "New here? Create an account"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex justify-end px-5 pt-3" style={{ background: PAPER }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={handleLogout}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="text-xs font-mono underline"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{ color: INK, opacity: 0.6 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Log out
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {children}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
